enhance: better status table for trawler (#857)
Co-authored-by: sandwich <dskvr@users.noreply.github.com>

diff --git a/apps/relaymon/.docker/Dockerfile b/apps/relaymon/.docker/Dockerfile
--- a/apps/relaymon/.docker/Dockerfile
+++ b/apps/relaymon/.docker/Dockerfile
@@ -68,6 +68,6 @@ COPY . .
 
 # Cache dependencies offline without trying to verify remote
 WORKDIR /app/nostr-watch/apps/relaymon
-RUN deno cache --reload --no-remote index.ts || echo "Dependency caching failed, will try at runtime"
+RUN deno cache --reload --no-remote --unstable-sloppy-imports index.ts || echo "Dependency caching failed, will try at runtime"
 
 ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
